<?php
return array (
  12 => 
  array (
    'groupid' => '12',
    'name' => '企业用户',
    'issystem' => '0',
    'starnum' => '1',
    'point' => '1',
    'allowmessage' => '65535',
    'allowvisit' => '0',
    'allowpost' => '1',
    'allowpostverify' => '0',
    'allowsearch' => '0',
    'allowupgrade' => '0',
    'allowsendmessage' => '1',
    'allowpostnum' => '0',
    'allowattachment' => '1',
    'price_y' => '0.00',
    'price_m' => '0.00',
    'price_d' => '0.00',
    'icon' => 'images/group/vip.jpg',
    'usernamecolor' => '#000000',
    'description' => '',
    'sort' => '1',
    'disabled' => '0',
  ),
  14 => 
  array (
    'groupid' => '14',
    'name' => '区县用户',
    'issystem' => '0',
    'starnum' => '1',
    'point' => '1',
    'allowmessage' => '0',
    'allowvisit' => '0',
    'allowpost' => '1',
    'allowpostverify' => '0',
    'allowsearch' => '0',
    'allowupgrade' => '0',
    'allowsendmessage' => '1',
    'allowpostnum' => '0',
    'allowattachment' => '1',
    'price_y' => '0.00',
    'price_m' => '0.00',
    'price_d' => '0.00',
    'icon' => 'images/group/vip.jpg',
    'usernamecolor' => '#000000',
    'description' => '',
    'sort' => '0',
    'disabled' => '0',
  ),
  13 => 
  array (
    'groupid' => '13',
    'name' => '园区用户',
    'issystem' => '0',
    'starnum' => '1',
    'point' => '11',
    'allowmessage' => '0',
    'allowvisit' => '0',
    'allowpost' => '1',
    'allowpostverify' => '0',
    'allowsearch' => '0',
    'allowupgrade' => '0',
    'allowsendmessage' => '1',
    'allowpostnum' => '0',
    'allowattachment' => '1',
    'price_y' => '0.00',
    'price_m' => '0.00',
    'price_d' => '0.00',
    'icon' => 'images/group/vip.jpg',
    'usernamecolor' => '#000000',
    'description' => '',
    'sort' => '0',
    'disabled' => '0',
  ),
  15 => 
  array (
    'groupid' => '15',
    'name' => 'gxw',
    'issystem' => '0',
    'starnum' => '1',
    'point' => '1',
    'allowmessage' => '0',
    'allowvisit' => '0',
    'allowpost' => '1',
    'allowpostverify' => '1',
    'allowsearch' => '0',
    'allowupgrade' => '0',
    'allowsendmessage' => '1',
    'allowpostnum' => '0',
    'allowattachment' => '1',
    'price_y' => '0.00',
    'price_m' => '0.00',
    'price_d' => '0.00',
    'icon' => 'images/group/vip.jpg',
    'usernamecolor' => '#000000',
    'description' => '',
    'sort' => '0',
    'disabled' => '0',
  ),
);
?>