<?php
return array (
  'title' => '产业类别',
  'style' => '2',
  'siteid' => '0',
  'data' => 
  array (
    3415 => 
    array (
      'linkageid' => '3415',
      'name' => '工程机械',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3415',
      'keyid' => '3387',
      'listorder' => '1',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3416 => 
    array (
      'linkageid' => '3416',
      'name' => '汽车及零部件',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3416',
      'keyid' => '3387',
      'listorder' => '2',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3420 => 
    array (
      'linkageid' => '3420',
      'name' => '新能源与节能环保',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3420',
      'keyid' => '3387',
      'listorder' => '3',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3417 => 
    array (
      'linkageid' => '3417',
      'name' => '食品包装与烟草',
      'style' => '0',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3417',
      'keyid' => '3387',
      'listorder' => '4',
      'description' => '',
      'setting' => 'array (
  \'level\' => \'0\',
)',
      'siteid' => '0',
    ),
    3423 => 
    array (
      'linkageid' => '3423',
      'name' => '纺织服装',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3423',
      'keyid' => '3387',
      'listorder' => '5',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3418 => 
    array (
      'linkageid' => '3418',
      'name' => '电子信息',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3418',
      'keyid' => '3387',
      'listorder' => '6',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3419 => 
    array (
      'linkageid' => '3419',
      'name' => '生物医药',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3419',
      'keyid' => '3387',
      'listorder' => '7',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3422 => 
    array (
      'linkageid' => '3422',
      'name' => '烟花爆竹',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3422',
      'keyid' => '3387',
      'listorder' => '8',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3425 => 
    array (
      'linkageid' => '3425',
      'name' => '家用电器',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3425',
      'keyid' => '3387',
      'listorder' => '9',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3426 => 
    array (
      'linkageid' => '3426',
      'name' => '电力装备',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3426',
      'keyid' => '3387',
      'listorder' => '10',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3427 => 
    array (
      'linkageid' => '3427',
      'name' => '材料',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3427',
      'keyid' => '3387',
      'listorder' => '11',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3421 => 
    array (
      'linkageid' => '3421',
      'name' => '轨道',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3421',
      'keyid' => '3387',
      'listorder' => '12',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3424 => 
    array (
      'linkageid' => '3424',
      'name' => '其它产业',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3424',
      'keyid' => '3387',
      'listorder' => '13',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
  ),
);
?>