<?php
return array (
  12 => 
  array (
    'modelid' => '12',
    'siteid' => '1',
    'name' => '企业模型',
    'description' => '企业模型',
    'tablename' => 'member_info',
    'setting' => '',
    'addtime' => '0',
    'items' => '0',
    'enablesearch' => '1',
    'disabled' => '0',
    'default_style' => '',
    'category_template' => '',
    'list_template' => '',
    'show_template' => '',
    'js_template' => '',
    'admin_list_template' => '',
    'member_add_template' => '',
    'member_list_template' => '',
    'sort' => '1',
    'type' => '2',
  ),
  29 => 
  array (
    'modelid' => '29',
    'siteid' => '1',
    'name' => 'gxw',
    'description' => 'gxw',
    'tablename' => 'member_gxw',
    'setting' => '',
    'addtime' => '0',
    'items' => '0',
    'enablesearch' => '1',
    'disabled' => '0',
    'default_style' => '',
    'category_template' => '',
    'list_template' => '',
    'show_template' => '',
    'js_template' => '',
    'admin_list_template' => '',
    'member_add_template' => '',
    'member_list_template' => '',
    'sort' => '2',
    'type' => '2',
  ),
  28 => 
  array (
    'modelid' => '28',
    'siteid' => '1',
    'name' => '园区模型',
    'description' => '园区模型',
    'tablename' => 'member_yuanqu',
    'setting' => '',
    'addtime' => '0',
    'items' => '0',
    'enablesearch' => '1',
    'disabled' => '0',
    'default_style' => '',
    'category_template' => '',
    'list_template' => '',
    'show_template' => '',
    'js_template' => '',
    'admin_list_template' => '',
    'member_add_template' => '',
    'member_list_template' => '',
    'sort' => '3',
    'type' => '2',
  ),
);
?>