<?php
return array (
  'title' => '所属园区',
  'style' => '2',
  'siteid' => '0',
  'data' => 
  array (
    3399 => 
    array (
      'linkageid' => '3399',
      'name' => '雨花经济开发区',
      'style' => '0',
      'parentid' => '3361',
      'child' => '0',
      'arrchildid' => '3399',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => 'array (
  \'level\' => \'0\',
)',
      'siteid' => '0',
    ),
    3400 => 
    array (
      'linkageid' => '3400',
      'name' => '天心经开区产业局',
      'style' => '',
      'parentid' => '3362',
      'child' => '0',
      'arrchildid' => '3400',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3401 => 
    array (
      'linkageid' => '3401',
      'name' => '望城经济开发区',
      'style' => '0',
      'parentid' => '3363',
      'child' => '0',
      'arrchildid' => '3401',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => 'array (
  \'level\' => \'0\',
)',
      'siteid' => '0',
    ),
    3403 => 
    array (
      'linkageid' => '3403',
      'name' => '岳麓工业集中区',
      'style' => '0',
      'parentid' => '3364',
      'child' => '0',
      'arrchildid' => '3403',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => 'array (
  \'level\' => \'0\',
)',
      'siteid' => '0',
    ),
    3405 => 
    array (
      'linkageid' => '3405',
      'name' => '隆平高科技园',
      'style' => '0',
      'parentid' => '3411',
      'child' => '0',
      'arrchildid' => '3405',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => 'array (
  \'level\' => \'0\',
)',
      'siteid' => '0',
    ),
    3414 => 
    array (
      'linkageid' => '3414',
      'name' => '浏阳经济开发区',
      'style' => '0',
      'parentid' => '3408',
      'child' => '0',
      'arrchildid' => '3414',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => 'array (
  \'level\' => \'0\',
)',
      'siteid' => '0',
    ),
    3443 => 
    array (
      'linkageid' => '3443',
      'name' => '金霞经济开发区',
      'style' => '',
      'parentid' => '3406',
      'child' => '0',
      'arrchildid' => '3443',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3445 => 
    array (
      'linkageid' => '3445',
      'name' => '宁乡经济开发区',
      'style' => '0',
      'parentid' => '3409',
      'child' => '0',
      'arrchildid' => '3445',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => 'array (
  \'level\' => \'0\',
)',
      'siteid' => '0',
    ),
    3447 => 
    array (
      'linkageid' => '3447',
      'name' => '长沙经济开发区',
      'style' => '0',
      'parentid' => '3365',
      'child' => '0',
      'arrchildid' => '3447',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '长沙经开区',
      'setting' => 'array (
  \'level\' => \'0\',
)',
      'siteid' => '0',
    ),
    3448 => 
    array (
      'linkageid' => '3448',
      'name' => '浏阳工业集中区',
      'style' => '',
      'parentid' => '3408',
      'child' => '0',
      'arrchildid' => '3448',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3449 => 
    array (
      'linkageid' => '3449',
      'name' => '长沙高新区',
      'style' => '',
      'parentid' => '3364',
      'child' => '0',
      'arrchildid' => '3449',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3365 => 
    array (
      'linkageid' => '3365',
      'name' => '长沙县',
      'style' => '',
      'parentid' => '0',
      'child' => '1',
      'arrchildid' => '3365,3447,3404',
      'keyid' => '3360',
      'listorder' => '1',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3408 => 
    array (
      'linkageid' => '3408',
      'name' => '浏阳市',
      'style' => '0',
      'parentid' => '0',
      'child' => '1',
      'arrchildid' => '3408,3414,3448',
      'keyid' => '3360',
      'listorder' => '2',
      'description' => '',
      'setting' => 'array (
  \'level\' => \'0\',
)',
      'siteid' => '0',
    ),
    3444 => 
    array (
      'linkageid' => '3444',
      'name' => '金洲新区工业集中区',
      'style' => '0',
      'parentid' => '3409',
      'child' => '0',
      'arrchildid' => '3444',
      'keyid' => '3360',
      'listorder' => '2',
      'description' => '',
      'setting' => 'array (
  \'level\' => \'0\',
)',
      'siteid' => '0',
    ),
    3409 => 
    array (
      'linkageid' => '3409',
      'name' => '宁乡县',
      'style' => '',
      'parentid' => '0',
      'child' => '1',
      'arrchildid' => '3409,3445,3444',
      'keyid' => '3360',
      'listorder' => '3',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3361 => 
    array (
      'linkageid' => '3361',
      'name' => '雨花区',
      'style' => '',
      'parentid' => '0',
      'child' => '1',
      'arrchildid' => '3361,3399',
      'keyid' => '3360',
      'listorder' => '4',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3362 => 
    array (
      'linkageid' => '3362',
      'name' => '天心区',
      'style' => '',
      'parentid' => '0',
      'child' => '1',
      'arrchildid' => '3362,3400',
      'keyid' => '3360',
      'listorder' => '5',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3411 => 
    array (
      'linkageid' => '3411',
      'name' => '芙蓉区',
      'style' => '',
      'parentid' => '0',
      'child' => '1',
      'arrchildid' => '3411,3405',
      'keyid' => '3360',
      'listorder' => '6',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3364 => 
    array (
      'linkageid' => '3364',
      'name' => '岳麓区',
      'style' => '',
      'parentid' => '0',
      'child' => '1',
      'arrchildid' => '3364,3403,3449',
      'keyid' => '3360',
      'listorder' => '7',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3406 => 
    array (
      'linkageid' => '3406',
      'name' => '开福区',
      'style' => '',
      'parentid' => '0',
      'child' => '1',
      'arrchildid' => '3406,3443',
      'keyid' => '3360',
      'listorder' => '8',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3363 => 
    array (
      'linkageid' => '3363',
      'name' => '望城县',
      'style' => '0',
      'parentid' => '0',
      'child' => '1',
      'arrchildid' => '3363,3401',
      'keyid' => '3360',
      'listorder' => '9',
      'description' => '',
      'setting' => 'array (
  \'level\' => \'0\',
)',
      'siteid' => '0',
    ),
    3404 => 
    array (
      'linkageid' => '3404',
      'name' => '星沙产业基地产业局',
      'style' => '',
      'parentid' => '3365',
      'child' => '0',
      'arrchildid' => '3404',
      'keyid' => '3360',
      'listorder' => '9',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
  ),
);
?>