<?php
return array (
  'title' => '项目类别',
  'style' => '2',
  'siteid' => '0',
  'data' => 
  array (
    3428 => 
    array (
      'linkageid' => '3428',
      'name' => '技术创新类',
      'style' => '0',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3428',
      'keyid' => '3381',
      'listorder' => '1',
      'description' => '',
      'setting' => 'array (
  \'level\' => \'0\',
)',
      'siteid' => '0',
    ),
    3429 => 
    array (
      'linkageid' => '3429',
      'name' => '技术改造类',
      'style' => '0',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3429',
      'keyid' => '3381',
      'listorder' => '2',
      'description' => '',
      'setting' => 'array (
  \'level\' => \'0\',
)',
      'siteid' => '0',
    ),
    3430 => 
    array (
      'linkageid' => '3430',
      'name' => '节能减排类',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3430',
      'keyid' => '3381',
      'listorder' => '3',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3432 => 
    array (
      'linkageid' => '3432',
      'name' => '创民富民类',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3432',
      'keyid' => '3381',
      'listorder' => '4',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3433 => 
    array (
      'linkageid' => '3433',
      'name' => '经济合作类',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3433',
      'keyid' => '3381',
      'listorder' => '5',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3434 => 
    array (
      'linkageid' => '3434',
      'name' => '市场拓展类',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3434',
      'keyid' => '3381',
      'listorder' => '6',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3440 => 
    array (
      'linkageid' => '3440',
      'name' => '工作调研',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3440',
      'keyid' => '3381',
      'listorder' => '7',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3439 => 
    array (
      'linkageid' => '3439',
      'name' => '要素保障',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3439',
      'keyid' => '3381',
      'listorder' => '8',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3431 => 
    array (
      'linkageid' => '3431',
      'name' => '信息化建设类',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3431',
      'keyid' => '3381',
      'listorder' => '9',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3435 => 
    array (
      'linkageid' => '3435',
      'name' => '中小企业发展',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3435',
      'keyid' => '3381',
      'listorder' => '10',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3436 => 
    array (
      'linkageid' => '3436',
      'name' => '平台、保障、调研类',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3436',
      'keyid' => '3381',
      'listorder' => '11',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3438 => 
    array (
      'linkageid' => '3438',
      'name' => '平台（园区）建设',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3438',
      'keyid' => '3381',
      'listorder' => '12',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3437 => 
    array (
      'linkageid' => '3437',
      'name' => '奖励类',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3437',
      'keyid' => '3381',
      'listorder' => '13',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3441 => 
    array (
      'linkageid' => '3441',
      'name' => '其他',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3441',
      'keyid' => '3381',
      'listorder' => '14',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
  ),
);
?>